export const academicAudit2025Schema = {
  id: "academic-audit-2025-26",
  title: "External Academic Audit",
  academicYear: "July, 2025 - June, 2026",
  ownerRole: "director-schools",
  sections: [
    {
      id: "school-department-information",
      title: "School / Department Information",
      fields: [
        "Name of the School / Department",
        "Year of Establishment",
        "Address",
        "Director's Name",
        "Director's Mail Id",
        "Program Offered with Intake",
        "Student's Strength",
        "Faculty Strength",
        "Academic Calendar",
      ],
    },
    {
      id: "part-a-academic-activities",
      title: "Part A - Academic Activities",
      tables: [
        "Board of Studies meetings conducted",
        "Syllabus revision feedback, analysis and ATR",
        "Outcome based education implementation",
        "NEP 2020 implementation status",
        "Best Practices at School level",
      ],
    },
    {
      id: "part-b-student-development",
      title: "Part B - Student Development & Progression",
      tables: [
        "Student Mentoring",
        "Students graduating",
        "Success Rate of Students",
        "Qualifying examinations",
        "Student awards",
        "Outgoing students placed",
        "Progression to Higher Studies",
        "Student Start-up details",
        "MOOCs / Value added / skill courses",
        "Alumni interactions",
        "Guest lectures / workshops / seminars",
        "Professional Body association & Student clubs",
        "Value added / Skill development courses",
        "Career guidance sessions",
        "Extension activities",
      ],
    },
    {
      id: "part-c-faculty-research",
      title: "Part C - Faculty Development & Research Activities",
      tables: [
        "Faculty strength and specialization",
        "Research Publications",
        "Books, chapters and conference proceedings",
        "Corporate training revenue",
        "Consultancy revenue",
        "Research funds",
        "E-Contents developed",
        "Fellowships / financial support",
        "Patents / copyrights",
        "Faculty Development Programs organized",
        "Faculty Development Programs attended",
        "Collaborations",
        "Functional MoUs",
      ],
    },
    {
      id: "part-d-swoc",
      title: "Part D - SWOC Analysis",
      fields: ["Strength", "Weaknesses", "Opportunities", "Challenges", "Any other information"],
    },
    {
      id: "part-e-observations",
      title: "Part E - Observations & Recommendations of the Audit",
      fields: ["Observations of the Academic Audit Team", "Recommendations of the Audit Team"],
    },
  ],
};
