export const administrativeAudit2025Schema = {
  id: "administrative-audit-2025-26",
  title: "Internal Administrative Audit",
  academicYear: "July, 2025 - June, 2026",
  ownerRoles: ["registrar", "hr", "dean-student-welfare", "dean-placement"],
  sections: [
    {
      id: "university-information",
      title: "A. University Information",
      fields: [
        "Name of the University",
        "Year of Establishment",
        "Address",
        "Pin Code",
        "Website",
        "Name of the Vice Chancellor",
        "Vice Chancellor e-Mail Id",
        "Name of Registrar",
        "Registrar e-Mail Id",
        "Accreditation status & Agency",
      ],
      tables: [
        "Courses Offered",
        "Total Number of Students in the university",
        "Statutory Body Meetings and ATR",
        "Audits Completed",
        "Scholarship Details",
      ],
    },
    {
      id: "faculty-staff-details",
      title: "B. Faculty and Staff Details",
      tables: [
        "Faculty Information",
        "Teaching Experience of Faculty in DYPIU",
        "Consolidated Faculty Experience",
        "Admin and Supporting Staff",
        "Administrative training / professional development",
      ],
    },
    {
      id: "infrastructure-details",
      title: "C. Infrastructure Details",
      tables: [
        "Building Infrastructure",
        "Library & Research Infrastructure",
        "E-resource availability",
        "I.T. Infrastructure",
        "Cultural, yoga, games and sports facilities",
        "Facilities for Divyangajan",
        "Research Resources",
      ],
    },
    {
      id: "student-affairs",
      title: "D. Student Activities - Dean / Director Student Affairs",
      ownerRole: "dean-student-welfare",
      tables: [
        "Hackathons and Ideation workshops",
        "Cultural Clubs and activities",
        "Sports clubs / teams and activities",
        "Community related activities",
        "Awards / Prizes / Recognitions",
      ],
    },
    {
      id: "placement-training",
      title: "E. Placement, Internship and Training Activities",
      ownerRole: "dean-placement",
      tables: [
        "Placement Activities",
        "Internship Activities",
        "Training / Skill development / Soft skills",
        "Industry Collaborations",
      ],
    },
    {
      id: "observations",
      title: "F. Observations & Recommendations of the Audit",
      fields: ["Observations of the Academic Audit Team", "Recommendations of the Audit Team"],
    },
  ],
};
