export const administrativeAuditMeta = {
  id: "administrative-audit-2025-26",
  title: "Internal Administrative Audit",
  academicYear: "July, 2025 - June, 2026",
  university: "D Y Patil International University Akurdi Pune",
  address: "Sector 29, Pradhikaran, Akurdi, Pune - Maharashtra, INDIA 411044",
  act: "Establishment by Maharashtra Act No. LXIII of 2017",
};

export const administrativeAuditModules = [
  {
    id: "section-a-university-information",
    number: "A",
    title: "University Information",
    owner: "Registrar",
    fields: [
      { id: "universityName", label: "Name of the University" },
      { id: "establishmentYear", label: "Year of Establishment" },
      { id: "address", label: "Address", type: "textarea" },
      { id: "pinCode", label: "Pin Code" },
      { id: "website", label: "Website" },
      { id: "viceChancellor", label: "Name of the Vice Chancellor" },
      { id: "vcEmail", label: "Vice Chancellor e-Mail Id", type: "email" },
      { id: "registrar", label: "Name of Registrar" },
      { id: "registrarEmail", label: "Registrar e-Mail Id", type: "email" },
      { id: "accreditation", label: "Accreditation status & Agency", type: "textarea" },
    ],
    tables: [
      {
        id: "coursesOffered",
        title: "1. Courses Offered",
        columns: ["Sr No", "Name of the Program", "Level (UG/PG)", "Intake", "Year of Commencement of the program"],
      },
      {
        id: "studentStatistics",
        title: "2. Total Number of Students in the university",
        columns: ["Sr No", "Category", "U.G.", "P.G.", "Ph.D.", "Value added / skill Courses"],
        initialRows: [
          { "Sr No": "1", Category: "Open" },
          { "Sr No": "2", Category: "OBC" },
          { "Sr No": "3", Category: "SC" },
          { "Sr No": "4", Category: "ST" },
          { "Sr No": "5", Category: "Others" },
        ],
      },
      {
        id: "statutoryBodies",
        title: "3. Statutory Body Meetings and ATR",
        columns: ["Sr No", "Body / Cell", "Meetings Conducted", "ATR Status", "Remarks / Link"],
        initialRows: [
          { "Sr No": "1", "Body / Cell": "Governing Body" },
          { "Sr No": "2", "Body / Cell": "Board of Management" },
          { "Sr No": "3", "Body / Cell": "Academic Council" },
          { "Sr No": "4", "Body / Cell": "Finance Committee" },
          { "Sr No": "5", "Body / Cell": "ICC" },
          { "Sr No": "6", "Body / Cell": "Student Grievance Cell" },
          { "Sr No": "7", "Body / Cell": "Faculty / Staff Grievance Cell" },
          { "Sr No": "8", "Body / Cell": "Anti Ragging Committee" },
          { "Sr No": "9", "Body / Cell": "Equal opportunity Cell" },
          { "Sr No": "10", "Body / Cell": "IQAC" },
          { "Sr No": "11", "Body / Cell": "Any Other Body / Cell" },
        ],
      },
      {
        id: "auditRecords",
        title: "4. Audits Completed",
        columns: ["Sr No", "Audit Type", "Completed Yes / No", "Date", "Remarks / Link"],
        initialRows: [
          { "Sr No": "1", "Audit Type": "Financial Audit" },
          { "Sr No": "2", "Audit Type": "Energy Audit" },
          { "Sr No": "3", "Audit Type": "Environmental Audit" },
          { "Sr No": "4", "Audit Type": "Green Audit" },
          { "Sr No": "5", "Audit Type": "Gender Audit" },
          { "Sr No": "6", "Audit Type": "Academic and Administrative Audit" },
        ],
      },
      {
        id: "scholarshipSummary",
        title: "5. Scholarship Details",
        columns: ["Sr No", "Year", "Title of Scholarship", "Number of the Students", "Amount received", "Awarding Agency", "Awarding Organization"],
      },
      {
        id: "scholarshipStudents",
        title: "6. Scholarship Student Details",
        columns: ["Sr No", "Year", "Title of Scholarship", "Name of the Students", "Amount received", "Awarding Agency"],
      },
    ],
  },
  {
    id: "section-b-faculty-staff-details",
    number: "B",
    title: "Faculty and Staff Details",
    owner: "HR",
    blocks: [
      {
        type: "tables",
        tables: [
          {
            id: "facultyInformation",
            title: "Faculty Information",
            columns: ["Sr No", "Cadre", "Required", "Regular", "Contract"],
            initialRows: [
              { "Sr No": "1", Cadre: "Professors" },
              { "Sr No": "2", Cadre: "Associate Professors" },
              { "Sr No": "3", Cadre: "Assistant Professor" },
              { "Sr No": "4", Cadre: "Total" },
            ],
          },
        ],
      },
      {
        type: "fields",
        fields: [
          { id: "phdQualification", label: "(a)(i) Faculty members with Ph.D qualification" },
          { id: "pgQualification", label: "(a)(ii) Post Graduation Qualification" },
          { id: "otherQualification", label: "(a)(iii) Any Other Qualification" },
          { id: "studentFacultyRatio", label: "(b) Student Faculty Ratio" },
        ],
      },
      {
        type: "tables",
        tables: [
          {
            id: "facultyTenure",
            title: "(c) Teaching Experience of the Faculty in DYPIU",
            columns: ["Sr No", "Tenure", "No. of Faculty"],
            initialRows: [
              { "Sr No": "1", Tenure: "More than 5 Years" },
              { "Sr No": "2", Tenure: "Between 3 to 5 Years" },
              { "Sr No": "3", Tenure: "Between 1 to 3 Years" },
              { "Sr No": "4", Tenure: "Below 1 Year" },
            ],
          },
          {
            id: "facultyExperience",
            title: "(d) Consolidated Experience of the teaching faculty considering outside experience",
            columns: ["S.No", "Name of the Faculty", "Designation", "Highest Qualification", "Date of Joining", "Experience in DYPIU", "Experience before joining DYPIU (Teaching)", "Total Experience"],
          },
          {
            id: "supportingStaff",
            title: "Details of Admin and Supporting Staff",
            notes: [
              "(a) Registrar",
              "(b) Dy Registrar / Asst Registrar",
              "(c) Librarian",
              "(d) Accountant",
              "(e) Lab Assistants",
              "(f) Technicians",
              "(g) Programmers",
              "(h) etc",
            ],
            columns: ["S.No", "Name of the Supporting Staff", "Designation", "Highest Qualification", "Date of Joining in DYPIU", "Experience in DYPIU", "Experience before joining DYPIU", "Total Experience"],
          },
          {
            id: "staffTraining",
            title: "Administrative training / professional development program organized for non-teaching staff",
            columns: ["Sr no", "Title of the Course", "Details of resource person", "Duration and date of conduction", "No of beneficiaries"],
          },
        ],
      },
    ],
  },
  {
    id: "section-c-infrastructure-details",
    number: "C",
    title: "Infrastructure Details",
    owner: "Registrar",
    tables: [
      {
        id: "buildingInfrastructure",
        title: "1. Building Infrastructure",
        columns: ["Sr No", "Facilities", "No."],
        initialRows: [
          { "Sr No": "1", Facilities: "Classrooms" },
          { "Sr No": "2", Facilities: "Laboratories" },
          { "Sr No": "3", Facilities: "Classroom with Smart Panel" },
          { "Sr No": "4", Facilities: "Classroom with Wi-Fi" },
          { "Sr No": "5", Facilities: "Seminar Hall with ICT Facilities" },
          { "Sr No": "6", Facilities: "Computer with ICT Facilities" },
          { "Sr No": "7", Facilities: "Play area facilities" },
          { "Sr No": "8", Facilities: "Common Rooms" },
          { "Sr No": "9", Facilities: "Staff rooms" },
          { "Sr No": "10", Facilities: "Others" },
        ],
      },
      {
        id: "libraryInfrastructure",
        title: "2. Library & Research Infrastructure",
        columns: ["Sr No", "Facilities", "No."],
        initialRows: [
          { "Sr No": "1", Facilities: "Books (Title and Volumes)" },
          { "Sr No": "2", Facilities: "E-books and Journals" },
          { "Sr No": "3", Facilities: "Journals" },
          { "Sr No": "4", Facilities: "Digital Data base" },
          { "Sr No": "5", Facilities: "CD / Video" },
          { "Sr No": "6", Facilities: "Library Automation" },
          { "Sr No": "7", Facilities: "Others" },
        ],
      },
      {
        id: "eResources",
        title: "E-resource Availability",
        columns: ["Sr No", "Facilities", "Availability", "Remarks"],
        initialRows: [
          { "Sr No": "1", Facilities: "e-journals" },
          { "Sr No": "2", Facilities: "Membership / subscription of e-ShodhSindhu" },
          { "Sr No": "3", Facilities: "Membership / subscription of Shodhganga" },
          { "Sr No": "4", Facilities: "Discipline-specific Databases" },
          { "Sr No": "5", Facilities: "Plagiarism Check software" },
          { "Sr No": "6", Facilities: "Licensed statistical software" },
          { "Sr No": "7", Facilities: "Discipline specific simulation software" },
        ],
      },
      {
        id: "itInfrastructure",
        title: "3. I.T. (Computer) Infrastructure",
        columns: ["Sr No", "Facilities", "No."],
        initialRows: [
          { "Sr No": "1", Facilities: "No. of Computers in Institute" },
          { "Sr No": "2", Facilities: "No. of Computer exclusively for students only" },
          { "Sr No": "3", Facilities: "No. of Servers" },
          { "Sr No": "4", Facilities: "No. of System Software's" },
          { "Sr No": "5", Facilities: "No. of Application Software's" },
          { "Sr No": "6", Facilities: "Internet Bandwidth" },
          { "Sr No": "7", Facilities: "No. of Wi-Fi Units" },
          { "Sr No": "8", Facilities: "Internet Connectivity" },
        ],
      },
      {
        id: "sportsFacilities",
        title: "4. Facilities for cultural activities, yoga, games, sports etc",
        columns: ["Sr No", "Facilities", "No."],
      },
      {
        id: "divyangajanFacilities",
        title: "5. Facilities for Divyangajan",
        columns: ["Sr No", "Facilities", "Available Yes / No"],
        initialRows: [
          { "Sr No": "1", Facilities: "Built environment with ramps / lifts for easy access to classrooms" },
          { "Sr No": "2", Facilities: "Divyangan friendly washrooms" },
          { "Sr No": "3", Facilities: "Signage including tactile path, lights, display boards and signposts" },
          { "Sr No": "4", Facilities: "Assistive technology and facilities for Divyangjan" },
          { "Sr No": "5", Facilities: "Provision for enquiry and information" },
        ],
      },
      {
        id: "researchResources",
        title: "6. Research Resources",
        columns: ["Sr No", "Facilities", "Availability", "Remarks"],
      },
    ],
  },
  {
    id: "section-d-student-activities",
    number: "D",
    title: "Student Activities (Extension and Outreach Activities)",
    owner: "Dean Student Welfare",
    note: "(Data to be provided by Dean Student Welfare)",
    tables: [
      {
        id: "hackathons",
        title: "1. Hackathons and Ideation workshops",
        columns: ["Sr No", "Activity details", "Organized by", "Date of conduction", "Number of beneficiaries / Participants"],
      },
      {
        id: "culturalActivities",
        title: "2. Cultural Clubs and activities and festivals",
        columns: ["Sr No", "Activity details", "Organized by", "Date of conduction", "Number of beneficiaries / Participants"],
      },
      {
        id: "sportsActivities",
        title: "3. Sports clubs / teams and activities",
        columns: ["Sr No", "Activity details", "Organized by", "Date of conduction", "Number of beneficiaries / Participants"],
      },
      {
        id: "communityActivities",
        title: "4. Community related activities",
        columns: ["Sr No", "Activity details", "Organized by", "Date of conduction", "Number of beneficiaries / Participants"],
      },
      {
        id: "studentAwards",
        title: "5. Awards / Prizes / Recognitions in curricular and extended curricular areas",
        columns: ["Sr No", "Name of the award", "Team / Individual", "Inter-University / State / National / International", "Name of the event", "Name of the student(s)"],
      },
    ],
  },
  {
    id: "section-e-placement-training",
    number: "E",
    title: "Student Activities (Extension and Outreach Activities)",
    owner: "Dean Placements",
    note: "(Data to be provided by Dean Placements)",
    blocks: [
      {
        type: "text",
        text: "Report on Placement, Internship and Training activities:",
      },
      {
        type: "fields",
        fields: [
          { id: "placementActivitiesHeading", kind: "heading", label: "(a) Placement Activities: (School wise list of the students to attach)" },
          { id: "companiesVisited", label: "(i) Number of companies Visited" },
          { id: "studentsPlaced", label: "(ii) Number of Students Placed" },
          { id: "highestSalary", label: "(iii) Highest Salary offered" },
          { id: "averageSalary", label: "(iv) Average salary offered" },
          { id: "medianSalary", label: "(v) Median Salary offered" },
          { id: "internshipActivitiesHeading", kind: "heading", label: "(b) Internship Activities: (School wise list of the students to attach)" },
          { id: "internshipOrganizations", label: "(i) Number of Organizations offered Internships" },
          { id: "studentsInternships", label: "(ii) Number of Students carried out Internships" },
          { id: "stipendInternships", label: "(iii) Number of Internships carried out with stipend" },
          { id: "totalInternships", label: "(iv) Total Number of Internships" },
        ],
      },
      {
        type: "tables",
        tables: [
          {
            id: "trainingActivities",
            title: "(c) Report on Training Activities / Skill development / soft skills conducted",
            columns: ["Sr No", "Academic Year", "Title of the Event", "Date of conduction", "No of students benefited"],
          },
          {
            id: "industryCollaborations",
            title: "(d) Industry Collaborations",
            columns: ["Sr No", "Name of the Organization / Institution / Industry with whom MoU is signed", "Year of signing MoU", "Duration of MoU", "List the actual activities under each MoU"],
          },
        ],
      },
    ],
  },
  {
    id: "section-f-observations-recommendations",
    number: "F",
    title: "Observations & Recommendations of the Audit",
    owner: "VC & IQAC",
    fields: [
      { id: "auditObservations", label: "Observations of the Academic Audit Team", type: "textarea" },
      { id: "auditRecommendations", label: "Recommendations of the Audit Team", type: "textarea" },
    ],
  },
];
